services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    depends_on:
      - redis
    volumes:
      - ./web:/var/www/html
      - ./php/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./php/supervisor/conf:/etc/supervisor/conf.d
      - ./php/supervisor/log:/var/log/supervisor
    networks:
      - web_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - php
    networks:
      - web_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - web_network

networks:
  web_network:
    external: true
